pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "author=dependabot[bot]"
      - "status-success=Travis CI - Pull Request"
    actions:
      merge:
        method: merge